export const WORLD_BG =
  "https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260609_231253_53c0854c-d13c-42c1-9fc0-17e87cd34091.png&w=1280&q=85";

/*
 * 首屏轮播与开场文案。原本是纯中文硬编码 —— 英文用户第一眼就会看到中文，
 * 所以改成按语言取。英文不是逐字翻译：中文这几句偏抒情、句式短，
 * 直译会变得生硬，这里按同样的语气重写。
 */
export const quotes = {
  zh: [
    "你可能会看到和你天差地别的故事",
    "也会发现那个远隔重洋的陌生朋友",
    "和你当时的心境如此相似",
    "和千万种声音共鸣",
    "也看到不同的人生",
    "每一个故事，都可能是一扇新的窗",
    "欢迎来到这里",
  ],
  en: [
    "You'll find lives nothing like your own",
    "And a stranger an ocean away",
    "who once felt exactly as you did",
    "Echo with a thousand voices",
    "and see lives unlike yours",
    "Every story can open a window",
    "Welcome — you're here",
  ],
};

export const introSlides = {
  zh: [
    ["有没有一件事", "即使过去很多年", "你仍然会向别人讲起？"],
    ["有没有一个决定", "改变了你后来的人生？"],
    ["欢迎来到这里", "和千万种声音共鸣", "也看到不同的人生"],
  ],
  en: [
    ["Is there something", "you still tell people about", "years after it happened?"],
    ["Was there a decision", "that changed everything after it?"],
    ["Welcome — you're here", "echo with a thousand voices", "and see lives unlike yours"],
  ],
};

export const gatewayCopy = {
  zh: {
    homeAria: "回到 StoryVerse 首页",
    introAria: "StoryVerse 开场介绍",
    skip: "跳过",
    scrollDown: "下滑",
    heroPrefix: "Begin",
    heroMain: "Your",
    heroBrand: "StoryVerse",
    heroBody: "各种意义上的异乡者，终会在这里相逢。",
    partner: "和千万种声音共鸣，也看到不同的人生。",
    previewTitle: ["真实故事。", "真实声音。"],
    previewSubtitle: "在 StoryVerse，看见和你天差地别的故事，也看见和你如此相似的人。",
    previousStory: "上一张故事卡片",
    nextStory: "下一张故事卡片",
    footerHowItWorks: "它如何运作",
    footerHowItWorksTitle: "第一次来到 StoryVerse？",
    footerHowItWorksBody:
      "你可以把它理解成一个从故事出发的共鸣星图：先找到一个能让你开口的入口，再写下经历，最后选择想听见相近还是不同的人生。",
    footerHowItWorksSteps: [
      "选择一个 Icebreaker。它不是分类考试，只是给记忆一个可以开始的地方。",
      "顺着提示写下故事。AI 只整理标签与故事页面，不会替你改写正文。",
      "发布后选择城市、人生阶段、主题三个方向，进入 StoryVerse 星图。",
    ],
    footerContact: "联系",
    footerRed: "小红书",
    footerEmail: "zicuili25@stu.pku.edu.cn",
    footerLegal: "法律",
    footerPrivacy: "隐私政策",
    footerTerms: "服务条款",
    loginEyebrow: "进入 StoryVerse",
    welcome: "欢迎来到",
    signup: "注册",
    login: "登录",
    nickname: "昵称",
    nicknamePlaceholder: "我们会保护您的身份隐私，取一个独属您的昵称吧",
    accountIdentifier: "账号",
    accountIdentifierPlaceholder: "4–20 位字母、数字或下划线",
    password: "密码",
    signupPasswordPlaceholder: "设置一个安全密码",
    loginPasswordPlaceholder: "输入你的密码",
    confirmPassword: "确认密码",
    securityQuestion: "密保问题",
    securityAnswer: "密保答案",
    createAccount: "创建账户",
    enter: "进入 StoryVerse",
    already: "已经有账户？",
    newHere: "第一次来到这里？",
    adminPrefix: "审核人员？",
    adminAction: "进入内容审核台",
    forgotPrefix: "忘记密码？",
    forgotAction: "点击找回",
    resetTitle: "找回密码",
    resetLead: "填写账号和注册时设置的密保答案，然后设置新密码。",
    resetAccount: "账号",
    resetPassword: "新密码",
    resetConfirm: "确认密码",
    resetCode: "密保答案",
    resetSubmit: "使用新密码",
    resetDone: "密码已经更新，可以使用新密码登录。",
  },
  en: {
    homeAria: "Back to StoryVerse home",
    introAria: "StoryVerse intro",
    skip: "Skip",
    scrollDown: "Scroll",
    heroPrefix: "Begin",
    heroMain: "Your",
    heroBrand: "StoryVerse",
    heroBody: "Strangers in every sense can still meet here.",
    partner: "Resonate with countless voices, and see different lives.",
    previewTitle: ["Real stories.", "Real voices."],
    previewSubtitle: "In StoryVerse, meet stories far from yours and people unexpectedly close to you.",
    previousStory: "Previous story card",
    nextStory: "Next story card",
    footerHowItWorks: "How it works",
    footerHowItWorksTitle: "New to StoryVerse?",
    footerHowItWorksBody:
      "Think of it as a resonance atlas built from lived stories: find an opening, write what happened, then choose whether you want to hear nearby or different lives.",
    footerHowItWorksSteps: [
      "Pick an icebreaker. It is not a test — just a place where memory can begin.",
      "Write your story in your own words. AI only organizes tags and the story page; it does not rewrite your voice.",
      "After publishing, choose city, life stage, and theme directions to enter the StoryVerse atlas.",
    ],
    footerContact: "Contact",
    footerRed: "RED",
    footerEmail: "zicuili25@stu.pku.edu.cn",
    footerLegal: "Legal",
    footerPrivacy: "Privacy Policy",
    footerTerms: "Terms of Service",
    loginEyebrow: "Step into StoryVerse",
    welcome: "Welcome to",
    signup: "Sign up",
    login: "Log in",
    nickname: "Nickname",
    nicknamePlaceholder: "Your identity stays private. Choose a name that belongs to you.",
    accountIdentifier: "Username",
    accountIdentifierPlaceholder: "4–20 letters, numbers or underscores",
    password: "Password",
    signupPasswordPlaceholder: "Create a strong password",
    loginPasswordPlaceholder: "Enter your password",
    confirmPassword: "Confirm password",
    securityQuestion: "Security question",
    securityAnswer: "Security answer",
    createAccount: "Create account",
    enter: "Enter StoryVerse",
    already: "Already have an account?",
    newHere: "New here?",
    adminPrefix: "Reviewer?",
    adminAction: "Open the moderation desk",
    forgotPrefix: "Forgot password?",
    forgotAction: "Recover",
    resetTitle: "Recover password",
    resetLead: "Enter your username and the security answer chosen at sign-up, then set a new password.",
    resetAccount: "Username",
    resetPassword: "New password",
    resetConfirm: "Confirm password",
    resetCode: "Security answer",
    resetSubmit: "Use new password",
    resetDone: "Your password has been updated. You can now sign in with it.",
  },
} as const;

export const clamp = (value: number, min = 0, max = 1) => Math.min(Math.max(value, min), max);
export const lerp = (a: number, b: number, t: number) => a + (b - a) * t;
export const easeInOut = (t: number) => (t < 0.5 ? 2 * t * t : -1 + (4 - 2 * t) * t);
export const privacyUrl = "https://icnh1tjz358q.feishu.cn/wiki/CG8Hw371bidxwDkT9YGck2kwnfe";
export const termsUrl = "https://icnh1tjz358q.feishu.cn/wiki/Wb3NwnFEWig5V0kTROGcd35nnlc";
