import type { Analysis, Draft, Story } from "./types";

export const icebreakers = [
  { id: "i1", question: "你曾经非常相信，但现在已经开始怀疑的一件事？", answer: "我曾相信只要足够忙碌，就一定在靠近理想。后来第一次停下来，才发现方向比速度重要。", tag: "身份", x: 14, y: 32 },
  { id: "i2", question: "哪座城市会带出你性格中最陌生的一面？", answer: "在重庆，我总想沿着没有目的地的阶梯一直走。好像迷路反而让我变得坦率。", tag: "城市", x: 36, y: 17 },
  { id: "i3", question: "最近一次灵光一闪是什么时候？", answer: "收拾外婆旧抽屉时，我突然明白，纪念不是保存所有东西，而是知道什么已经留在身上。", tag: "成长", x: 68, y: 28 },
  { id: "i4", question: "一件起初像自我提升、后来却伤害你的事？", answer: "我把每一分钟都排满，以为那叫自律。直到某天朋友问我，上一次真正开心是什么时候。", tag: "反思", x: 82, y: 54 },
  { id: "i5", question: "一个从未说出口的好奇？", answer: "如果小时候搬家前没有和她告别，她后来还会偶尔想起我吗？", tag: "关系", x: 48, y: 66 },
];

export const guides = [
  {
    id: "agency",
    icon: "↗",
    construct: "自主能动性",
    title: "命运在我手中",
    shortTitle: "命运",
    en: "In My Hands",
    enShort: "Agency",
    prompt: "有没有一件事让你突然意识到「命运永远掌握在自己手里」？具体发生了什么？",
    enPrompt: "Was there a moment when you realized your life was still in your own hands? What happened?",
    examples: "有段时间，我面临学业、工作、生活的三重压力，但意外的是，最后所有我定下的目标全都靠自己实现了。",
    enExamples: "There was a time when school, work, and life pressed on me all at once. Somehow, every goal I set was eventually reached by my own effort.",
    definition: "叙事主角改变自身命运、影响周遭他人环境的能力，常体现为自我掌控、自我赋权、成就、社会地位；高自主叙事突出个人成就、掌控人生走向。",
  },
  {
    id: "communion",
    icon: "♥",
    construct: "社群联结性",
    title: "离不开的TA们",
    shortTitle: "联结",
    en: "The Ones Who Hold Me",
    enShort: "Bond",
    prompt: "哪个瞬间，因为某个陌生、朋友或动物等，让你又爱上了这个世界？",
    enPrompt: "Was there a moment when a stranger, friend, animal, or someone else made you fall in love with the world again?",
    examples: "我很喜欢变魔术，那天我在社团意外认识了一群魔术同好者，大家在一起交流着共同热爱的事，我真切感受到无条件的爱与温暖。",
    enExamples: "I love magic. One day in a club, I unexpectedly met a group of people who loved it too. Sharing that passion made me feel unconditional warmth.",
    definition: "主角通过爱、友谊、沟通、集体归属建立人际联结，叙事核心是亲密、关怀、归属感。",
  },
  {
    id: "redemption",
    icon: "◷",
    construct: "救赎叙事",
    title: "轻舟已过万重山",
    shortTitle: "救赎",
    en: "Past Ten Thousand Mountains",
    enShort: "Relief",
    prompt: "哪件事发生的时候你觉得天都要塌了，但如今回头看却发现「轻舟已过万重山」？",
    enPrompt: "What once felt like the sky was falling, but now feels like something you have already sailed through?",
    examples: "我在公司干了五年突然被裁。当时觉得天塌了，失眠整整一个月。结果不久之后，之前一直想创业但没敢动手的前同事找我合伙，现在比上班赚了三倍。",
    enExamples: "After five years at a company, I was suddenly laid off. I could not sleep for a month. Later, a former colleague asked me to start a business together — now I earn three times more than before.",
    definition: "明确消极、痛苦的事件，最终导向积极、正向结果；前期负面经历被后续美好体验“救赎”。",
  },
  {
    id: "contamination",
    icon: "◎",
    construct: "污损叙事",
    title: "黑色苦痛",
    shortTitle: "苦痛",
    en: "Dark Irony",
    enShort: "Irony",
    prompt: "有没有哪次你以为抓住了幸福或者赢了，但命运却在暗中给你开了一个巨大的玩笑？",
    enPrompt: "Was there a time when you thought you had won or found happiness, only for life to play a dark joke on you?",
    examples: "本来升职我特别开心，后来才知道这次晋升是以我的好友被辞退为代价换来的。",
    enExamples: "I was thrilled about my promotion, until I learned it came at the cost of my close friend being laid off.",
    definition: "原本积极美好的事件急转直下，负面情绪彻底覆盖、消解之前所有正向体验。",
  },
  {
    id: "exploration",
    icon: "✦",
    construct: "探索型叙事",
    title: "和自己对话",
    shortTitle: "成长",
    en: "A Talk With Myself",
    enShort: "Growth",
    prompt: "如果把过去的自己拉出来和现在的你对话，有什么事让你可以自信地和Ta说：「现在的我长大了」？",
    enPrompt: "If your past self could talk with you now, what story would let you say with confidence: “I have grown up”?",
    examples: "那一年我的人生跌入谷底……但我慢慢重建生活，变成更独立、情绪稳定的人。那段时光满是痛苦、不断试错，回头看，正是它塑造了现在的我。",
    enExamples: "That year, my life hit bottom. Slowly, I rebuilt it and became more independent and emotionally steady. Looking back, that painful trial-and-error shaped who I am now.",
    definition: "叙事中展现深度自我探索，形成丰富、立体的自我认知，高分代表充分的自我复盘与成长探索。",
  },
  {
    id: "resolution",
    icon: "○",
    construct: "积极完整化解",
    title: "解开心结",
    shortTitle: "释怀",
    en: "Untying the Knot",
    enShort: "Closure",
    prompt: "你有没有什么很久才解开的心结，最后是怎么放下的？",
    enPrompt: "Was there a knot in your heart that took a long time to untie? How did you finally let it go?",
    examples: "多年过去，我终于原谅了弟弟的过错，接纳他所有不完美，我们的关系也因此更加亲近。",
    enExamples: "After many years, I finally forgave my younger brother and accepted his imperfections. Our relationship became closer because of it.",
    definition: "故事冲突得到妥善收尾，结局正向圆满。",
  },
  {
    id: "other",
    icon: "＋",
    construct: "其他",
    title: "其他",
    shortTitle: "其他",
    en: "Other",
    enShort: "Other",
    prompt: "写下一个只属于你的故事入口。",
    enPrompt: "Write an entry point that belongs only to your story.",
    examples: "自由编辑你的引导标题或提示。",
    enExamples: "Freely write your own prompt or story entry point.",
    definition: "用户自定义故事入口。",
  },
];

export const stories: Story[] = [
  {
    id: "s1", title: "把故乡装进一只蓝色行李箱", excerpt: "离开昆明那天，我只带走了外婆缝的一块蓝布……",
    body: "离开昆明那天，我只带走了外婆缝的一块蓝布。它本来是要做成枕套的，边缘还有没收好的线。抵达上海后的第一个雨夜，我把它铺在陌生出租屋的桌上，忽然觉得房间里有了一小块故乡。后来我搬过三次家，那块布一直在箱子最上面。它没有让我不再想家，却让我明白，归属感有时不是一个地点，而是一件愿意一直带着走的小东西。",
    author: "星旅人 042", city: "昆明", stage: "初入职场", theme: "迁移", emotion: "想念", meaning: "归属", perspective: "温柔现实主义", people: ["自己", "家人"], readMinutes: 3, visualStatus: "ready", x: 15, y: 23,
  },
  {
    id: "s2", title: "父亲第一次问我累不累", excerpt: "我们一直不擅长说柔软的话，直到那个凌晨……",
    body: "我们一直不擅长说柔软的话。大学毕业后的那个凌晨，我加班回家，发现父亲还坐在客厅。他没有问工作怎么样，只递给我一碗已经热过两次的汤，然后问：累不累？那三个字让我突然想起小时候每一次发烧，他也是这样坐着。我们之间并没有因为那一晚变得无话不谈，但我开始学会辨认他沉默里的关心。",
    author: "匿名星点 117", city: "广州", stage: "初入职场", theme: "家庭", emotion: "温暖", meaning: "理解", perspective: "关系修复", people: ["自己", "家人"], readMinutes: 2, visualStatus: "generating", x: 39, y: 38,
  },
  {
    id: "s3", title: "二十七岁重新学会迷路", excerpt: "在东京交换的第三周，我故意没有打开地图……",
    body: "在东京交换的第三周，我故意没有打开地图。那段时间我对未来极度焦虑，仿佛每一步都必须有产出。迷路的两个小时里，我经过一间旧书店、一所放学的小学和一条没有游客的河。没有任何事情因此被解决，但我久违地感到自己正在生活，而不是完成一张无限延伸的任务清单。",
    author: "星旅人 236", city: "东京", stage: "青年探索", theme: "成长", emotion: "释然", meaning: "自由", perspective: "慢下来", people: ["自己", "陌生人"], readMinutes: 3, visualStatus: "ready", x: 66, y: 18,
  },
  {
    id: "s4", title: "没有寄出的那封邮件", excerpt: "辞职前我写了很长一封邮件，最后只留下六个字……",
    body: "辞职前我写了很长一封邮件，解释那些被忽视的努力和我为什么失望。修改到深夜，最后却删掉所有控诉，只留下“谢谢，我决定离开”。过去我把离开理解为失败，后来才意识到，有些选择不是为了证明谁错了，而是停止把自己交给一个已经无法生长的地方。",
    author: "匿名星点 081", city: "深圳", stage: "职业转折", theme: "工作", emotion: "坚定", meaning: "边界", perspective: "自我选择", people: ["自己", "同事"], readMinutes: 3, visualStatus: "failed", x: 79, y: 41,
  },
  {
    id: "s5", title: "和母亲在厨房里重新认识", excerpt: "回家住的那个月，我们第一次像两个成年人那样聊天……",
    body: "回家住的那个月，我和母亲每天在厨房一起准备晚饭。以前她总问我工作和婚姻，像在检查一张人生进度表。那天我终于问她，年轻时真正想做什么。她沉默很久，说想当一名地理老师。我们第一次不是作为母女，而是作为两个曾经犹豫、也曾错过什么的成年人聊天。",
    author: "星旅人 305", city: "成都", stage: "成年回望", theme: "家庭", emotion: "复杂", meaning: "看见", perspective: "代际理解", people: ["自己", "家人"], readMinutes: 4, visualStatus: "blocked", x: 26, y: 68,
  },
  {
    id: "s6", title: "我们在毕业典礼后走散", excerpt: "没有争吵，也没有正式告别，只是消息越来越短……",
    body: "没有争吵，也没有正式告别，只是消息越来越短。毕业典礼那天我们约定每年见面，第三年却谁也没有再提。很久以后我才接受，有些关系不是因为做错了什么才结束。共同生活曾把我们放在同一条路上，时间又温和地把路分开。记得并不意味着必须回去。",
    author: "匿名星点 193", city: "武汉", stage: "大学毕业", theme: "关系", emotion: "遗憾", meaning: "告别", perspective: "接纳变化", people: ["朋友"], readMinutes: 2, visualStatus: "ready", x: 54, y: 73,
  },
  {
    id: "s7", title: "第一次用自己的名字签字", excerpt: "那张租房合同很普通，却像一份迟来的独立宣言……",
    body: "那张租房合同很普通，却像一份迟来的独立宣言。签字时我的手有点抖，因为这意味着房租、水电和每一个决定都由自己承担。晚上坐在还没有家具的房间里，我既害怕又兴奋。独立不是突然变得无所不能，而是终于允许自己在犯错后收拾残局。",
    author: "星旅人 410", city: "北京", stage: "独自生活", theme: "身份", emotion: "勇气", meaning: "独立", perspective: "成长实践", people: ["自己"], readMinutes: 2, visualStatus: "ready", x: 89, y: 69,
  },
];

export const emptyDraft: Draft = {
  guide: "", customGuide: "", title: "", body: "", mood: "", time: "", stage: "", age: "", gender: "",
  city: "", cityEn: "", cityCountry: "", cityLat: null, cityLon: null, people: [],
  startedAt: Date.now(), edits: 0, pastedChars: 0, saves: 0, savedAt: 0,
};

export const mockAnalysis: Analysis = {
  suggestedTitle: "雨停之前，我学会了告别",
  tags: {
    topic: ["成长", "关系"],
    emotion: ["释然", "想念"],
    meaning: ["告别", "归属"],
    perspective: ["自我理解"],
  },
  arc: ["一个熟悉的生活被打破", "在迟疑中重新看见过去", "一次微小选择改变了理解", "带着新的意义继续生活"],
};
